-- ---------------------------------------------------------------------
-- tool_invocations：每次 Tool 调用记录（第 17 节，审计表 day one 写入）
-- 与 sqlite 轨同版本号、同列名同约束，仅方言不同：
--   SQLite 布尔落 INTEGER(0/1)、时间戳落 TEXT(ISO-8601)；
--   PostgreSQL 用原生 BOOLEAN 与 TIMESTAMP，自增主键用 IDENTITY。
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tool_invocations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id     VARCHAR(64) NOT NULL,
    tool_name      VARCHAR(64) NOT NULL,
    input_json     TEXT,                                 -- 调用参数
    result_json    TEXT,                                 -- 执行结果
    success        BOOLEAN     NOT NULL,
    error_message  TEXT,                                 -- 可空
    duration_ms    BIGINT      NOT NULL DEFAULT 0,
    created_at     TIMESTAMP   NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_tool_invocations_session ON tool_invocations(session_id);
