-- ---------------------------------------------------------------------
-- memory_entries：长期记忆条目（第 22 节，结构化库档的后端）
-- 与 sqlite 轨同版本号、同列名同约束；方言差异照既有 V17~V19 的口径：
--   自增主键 → 标识列（GENERATED BY DEFAULT AS IDENTITY）
--   时间戳 → 原生 TIMESTAMP（sqlite 轨落 TEXT/ISO-8601）
-- 分区语义与 sqlite 轨一致：核心区全量取不截断，归档区只带最近 N 条。
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS memory_entries (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope       VARCHAR(16) NOT NULL,                    -- CORE / ARCHIVAL
    content     TEXT        NOT NULL,
    created_at  TIMESTAMP   NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_memory_entries_scope ON memory_entries(scope);
