-- ---------------------------------------------------------------------
-- scheduled_tasks：定时任务登记信息与运行状态（第 28 节，§8.5 / §9.2）
-- 与 sqlite 轨同版本号、同列名同约束；方言差异照既有 V17~V20 的口径：
--   自增主键 → 标识列（GENERATED BY DEFAULT AS IDENTITY）
--   布尔     → 原生 BOOLEAN
--   时间戳   → 原生 TIMESTAMP（sqlite 轨落 TEXT/ISO-8601）
--
-- 定义来源仍是 Agent 配置的 schedules 字段——这张表只存"状态与历史"，
-- 不作为定义源；重启时从配置重新协调（reconcile），一次性登记。
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS scheduled_tasks (
    schedule_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_name   VARCHAR(64) NOT NULL,
    schedule_key   VARCHAR(64) NOT NULL,               -- Agent 内配置键，同一 Profile 内唯一
    display_name   TEXT,                               -- 展示名称，不参与运行态定位
    cron           TEXT        NOT NULL,
    zone           TEXT        NOT NULL DEFAULT 'Asia/Shanghai',
    message        TEXT        NOT NULL,
    enabled        BOOLEAN     NOT NULL DEFAULT TRUE,  -- 管理台开关；关到点即跳过
    retired        BOOLEAN     NOT NULL DEFAULT FALSE, -- 配置删除/改 key 后退役；状态与历史保留
    next_run_at    TIMESTAMP,
    last_run_at    TIMESTAMP,
    last_status    TEXT,                               -- success / failed
    run_count      BIGINT      NOT NULL DEFAULT 0,
    updated_at     TIMESTAMP   NOT NULL,
    CONSTRAINT uk_scheduled_task UNIQUE (profile_name, schedule_key)
);
CREATE INDEX IF NOT EXISTS idx_scheduled_tasks_profile ON scheduled_tasks(profile_name);